p8105\_hw3\_ml4198
================
Matthew Lawlor
10/12/2020

## Problem 1

``` r
library(p8105.datasets)
data("instacart")
```

This is a dataframe of Instacart orders with 17 variables and 1,384,617
entries. Key variables are user\_id, order\_id, product\_id, aisle\_id.

``` r
instacart %>% 
    group_by(aisle_id) %>% 
  summarize(
    n_obs = n()
    ) %>% 
  mutate(
    freq_rank = min_rank(desc(n_obs))
    ) %>% 
  filter(freq_rank < 10)
```

    ## `summarise()` ungrouping output (override with `.groups` argument)

    ## # A tibble: 9 x 3
    ##   aisle_id  n_obs freq_rank
    ##      <int>  <int>     <int>
    ## 1       21  41699         5
    ## 2       24 150473         2
    ## 3       83 150609         1
    ## 4       84  32644         7
    ## 5       91  26240         9
    ## 6      107  31269         8
    ## 7      115  36617         6
    ## 8      120  55240         4
    ## 9      123  78493         3

There are 134 aisles, and the most commonly ordered from are aisle 83
(150609 orders), 24 (150473 orders), and 123 (78493 orders).

``` r
instacart %>% 
    group_by(aisle_id) %>% 
  summarize(
    n_obs = n()
    ) %>% 
  mutate(
    freq_rank = min_rank(desc(n_obs))
    ) %>% 
  filter(n_obs > 10000) %>% 
  arrange(freq_rank)
```

    ## `summarise()` ungrouping output (override with `.groups` argument)

    ## # A tibble: 39 x 3
    ##    aisle_id  n_obs freq_rank
    ##       <int>  <int>     <int>
    ##  1       83 150609         1
    ##  2       24 150473         2
    ##  3      123  78493         3
    ##  4      120  55240         4
    ##  5       21  41699         5
    ##  6      115  36617         6
    ##  7       84  32644         7
    ##  8      107  31269         8
    ##  9       91  26240         9
    ## 10      112  23635        10
    ## # … with 29 more rows
