---
title: "p8105_hw3_ml4198"
author: "Matthew Lawlor"
date: "10/12/2020"
output: github_document
---

```{r setup, include=FALSE}
library (tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
  
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r data}
library(p8105.datasets)
data("instacart")
```

This is a dataframe of Instacart orders with 17 variables and 1,384,617 entries. Key variables are user_id, order_id, product_id, aisle_id.

```{r}
instacart %>% 
    group_by(aisle_id) %>% 
  summarize(
    n_obs = n()
    ) %>% 
  mutate(
    freq_rank = min_rank(desc(n_obs))
    ) %>% 
  filter(freq_rank < 10)
```

There are 134 aisles, and the most commonly ordered from are aisle 83 (150609 orders), 24 (150473 orders), and 123 (78493 orders).

```{r}
instacart %>% 
    group_by(aisle_id) %>% 
  summarize(
    n_obs = n()
    ) %>% 
  mutate(
    freq_rank = min_rank(desc(n_obs))
    ) %>% 
  filter(n_obs > 10000) %>% 
  arrange(freq_rank) %>% 
  ggplot(aes(x = freq_rank, y = n_obs)) +
  geom_point() + 
  scale_x_continuous(
    breaks = c(1, 5, 10, 15, 20, 25, 30, 35),
    minor_breaks = c(1:39)) +
  labs(
    x = "Aisle",
    y = "Number of items ordered"
  )
```

labs(
    title = "Temperature plot",
    x = "Minimum Daily Temperature (C)",
    y = "Maximum Daily Temperature (C)",
    caption = "Data from the rnoaa packaege: temperatures in 2017"
